Se agrega la barra de navegacion inferior para "mis plantas" screen
ripsamuel/huerta-digital pull request #5
Opened 2022-11-24 06:32 UTC by ripsamuel

2022-11-24 06:34 UTC, ripsamuel commented
![Screen Shot 2022-11-24 at 1 32 58 AM](https://user-images.githubusercontent.com/104223467/203711015-3ae7f244-9b6a-4b5e-9ee3-f7a8b1978420.png)

2023-01-20 16:42 UTC, calderonsteven requested changes
Some small changes to address.

2023-01-20 16:42 UTC, calderonsteven commented on src/App.js
> +// import { PlantList } from "./components/PlantList";
Please remove commented code

2023-01-20 16:42 UTC, calderonsteven commented on src/App.js
> +];
please format/indent the whole file so it looks better

2023-01-20 16:42 UTC, calderonsteven commented on src/components/BottomNavigationMUI.js
> +// import Home from "@mui/icons-material/Home";
remove commented code

2023-08-10 15:52 UTC, merged